# Generated by Django 5.2.8 on 2025-11-15 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoDiseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='disenos/archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'dwg', 'jpg', 'jpeg', 'png', 'svg'])])),
                ('nombre', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('orden', 'Vinculado a Orden'), ('libre', 'Independiente / Cliente')], default='libre', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diseño',
                'verbose_name_plural': 'Diseños',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
