# Generated by Django 5.2.8 on 2025-11-15 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseno', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseno',
            name='orden',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío para diseños independientes o prediseños', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disenos', to='produccion.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='archivodiseno',
            name='diseno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='diseno.diseno'),
        ),
    ]
