# Generated by Django 5.2.8 on 2025-11-15 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='Razón Social')),
                ('nit', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('tipo_tablero', models.CharField(max_length=200, verbose_name='Tipo de Tablero')),
                ('dimensiones', models.CharField(max_length=200, verbose_name='Dimensiones')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='ordenes_archivos/%Y/%m/', verbose_name='Archivo Adjunto (Plano, PDF, etc.)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizaciones.cotizacion', verbose_name='Cotización Relacionada')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MaterialProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Material')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='produccion.ordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Material de Producción',
                'verbose_name_plural': 'Materiales de Producción',
            },
        ),
    ]
