# Generated by Django 5.2 on 2025-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='numero',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
