# Generated by Django 5.2.8 on 2025-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='cotizacion',
            old_name='updated_at',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='cotizacion',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
